App\Calendar\Domain\Model\Calendar:
  type: entity
  table: calendar
  id:
    id:
      column: id
      type: calendarId
      nullable: false
  fields:
    name:
      type: string
    description:
      type: string